name: Build the flutter version of the RustDesk
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: nightly
env:
  SCITER_RUST_VERSION: '1.75'
  RUST_VERSION: '1.75'
  MAC_RUST_VERSION: '1.81'
  CARGO_NDK_VERSION: 3.1.2
  SCITER_ARMV7_CMAKE_VERSION: 3.29.7
  SCITER_NASM_DEBVERSION: 2.15.05-1
  LLVM_VERSION: 15.0.6
  FLUTTER_VERSION: 3.24.5
  ANDROID_FLUTTER_VERSION: 3.24.5
  FLUTTER_WINDOWS_ARM_VERSION: 3.44.9
  FLUTTER_ELINUX_VERSION: 3.16.9
  TAG_NAME: ${{ inputs.upload-tag }}
  VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
  VCPKG_COMMIT_ID: 9e593bb18ea69cc5095e012465dcd675a822ed0d
  ARMV7_VCPKG_COMMIT_ID: 6f29f12e82a8293156836ad81cc9bf5af41fe836
  VERSION: 1.4.9
  NDK_VERSION: r28c
  ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
  MACOS_P12_BASE64: ${{ secrets.MACOS_P12_BASE64 }}
  UPLOAD_ARTIFACT: ${{ inputs.upload-artifact }}
  SIGN_BASE_URL: ${{ secrets.SIGN_BASE_URL }}-2
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          submodules: recursive
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Generate SBOM
        run: "syft dir:. \\\n  -o cyclonedx-json=rustdesk.sbom.json\n"
      - name: Publish Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        if: env.UPLOAD_ARTIFACT == 'true'
        with:
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          files: 'rustdesk.sbom.json

            '
  generate-bridge:
    uses: ./.github/workflows/bridge.yml
  build-for-linux-flutter:
    runs-on: ubuntu-22.04
    needs:
      - generate-bridge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore bridge files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: bridge-artifact
      - name: Install dependencies
        run: |
          sudo apt-get install ca-certificates -y
          sudo apt-get update -y
          sudo apt-get install -y clang cmake gcc git g++ libclang-dev libgtk-3-dev llvm-dev nasm ninja-build pkg-config wget libxdo-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev libxtst-dev libxcb1-dev libx11-xcb-dev libxcb-damage0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-xinerama0-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libgbm-dev libusb-1.0-0-dev libwayland-dev libxkbcommon-dev libdrm-dev libpam0g-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libappindicator3-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-unknown-linux-gnu
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Enable Desktop
        run: 'flutter config --enable-linux-desktop

          '
      - name: Build
        run: python3 ./build.py --flutter
      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-linux-deb
          path: rustdesk-*.deb
